# SITE CONFIGURATION
baseurl: "/kanji"
url: "https://sylhare.github.io/"

title: Kanji radicals
description: Japanese radicals presented as learning cards.

google_analytics: "G-YPX3TXS4S4"

# BUILD SETTINGS
sass:
  style: compressed
plugins: [ jekyll-seo-tag ]
exclude: [ ".jekyll-cache", "Gemfile", "Gemfile.lock", "*.gemspec", "*.gem", ".idea",
           "resources", "LICENSE", "README.md", "node_modules", "node_modules/**",
           "radical-selector/node_modules", "radical-selector/node_modules/**",
           "radical-selector/server/node_modules", "radical-selector/server/node_modules/**",
           "assets/js/gulp", ".sass-cache/", "vendor/*" ]