# SITE CONFIGURATION
baseurl: "/kanji"
url: "https://sylhare.github.io/"

title: Kanji radicals
description: Japanese radicals presented as learning cards.

google_analytics: "UA-142123817-1"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "*.gemspec", "*.gem", ".idea",
          "resources", "LICENSE", "README.md", "assets/js/gulp"]
