name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        ruby: ['3.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Start Jekyll server
        run: |
          bundle exec jekyll serve --port 4000 --host 0.0.0.0 &
          echo "JEKYLL_PID=$!" >> $GITHUB_ENV
        env:
          JEKYLL_ENV: production

      - name: Wait for Jekyll server to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:4000/kanji/; do sleep 2; done'
          echo "Jekyll server is ready!"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: scripts/cypress/cypress.config.js
          wait-on: 'http://localhost:4000/kanji/'
          wait-on-timeout: 120
          browser: chrome
          record: false
          install: false

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: scripts/cypress/screenshots
          retention-days: 7

      - name: Upload videos on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: scripts/cypress/videos
          retention-days: 7

      - name: Stop Jekyll server
        if: always()
        run: |
          if [ ! -z "$JEKYLL_PID" ]; then
            kill $JEKYLL_PID || true
          fi
