name: Build

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.4' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build jekyll site
        run: bundle exec jekyll build --future
        env:
          JEKYLL_ENV: production
