name: Build

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.3' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install github-pages gem
        run: |
          gem install github-pages
      - name: Install
        run: bundle install
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Build the site in the container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest \
          /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
