name: HTML Proofer

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: bundle install

    - name: Install html proofer
      run: gem install html-proofer 

    - name: Build project
      run: bundle exec jekyll build --strict_front_matter -d _site/kanji # So that the html proofed understand local links

    - name: html check
      run: htmlproofer --help && htmlproofer --assume-extension ./_site --allow-hash-href --checks
      continue-on-error: true

