name: HTML Proofer

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: sylhare/jekyll:ubuntu

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Use US Language
      run : |
        locale -a
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8

    - name: Install dependencies
      run: bundle install

    - name: Build project 
      run: bundle exec jekyll build --strict_front_matter -d _site/kanji

    - name: html check
      run: htmlproofer --assume-extension ./_site --allow-hash-href --check-favicon --check-html --check-opengraph

