name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://sylhare/jekyll:ubuntu
    - name: Build jekyll website
      run: |
        bundle install
        bundle exec jekyll build --strict_front_matter
